backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pagina"
    label: "PÃ¡gina Principal"
    files:
      - file: "index.html"
        label: "Inicio"
        name: "inicio"
        fields:
          - {label: "Contenido", name: "body", widget: "markdown"}
